-- Artwork results are generated by the server-side originality workflow. Artists
-- must not be able to forge a "clear" result through the public data API.
DROP POLICY IF EXISTS "Artists submit own country-matched artworks" ON public.artworks;
DROP POLICY IF EXISTS "Artists edit submissions admins publish" ON public.artworks;

CREATE POLICY "Admins manage artworks" ON public.artworks
  FOR INSERT TO authenticated WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Admins update artworks" ON public.artworks
  FOR UPDATE TO authenticated USING (public.has_role(auth.uid(), 'admin'))
  WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE OR REPLACE FUNCTION public.prevent_unchecked_artwork_publication()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.status IN ('published', 'sold')
     AND (NEW.originality_status <> 'clear' OR NEW.originality_checked_at IS NULL) THEN
    RAISE EXCEPTION 'Artwork must pass an originality check before publication';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS enforce_artwork_originality_before_publication ON public.artworks;
CREATE TRIGGER enforce_artwork_originality_before_publication
  BEFORE INSERT OR UPDATE OF status, originality_status, originality_checked_at ON public.artworks
  FOR EACH ROW EXECUTE FUNCTION public.prevent_unchecked_artwork_publication();
